apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-archiver
spec:
  schedule: "0/1 * * * *" # Every 1 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: archiver
            image: busybox:1.36
            command:
            - /bin/sh
            - -c
            - |
              tar czvf /logs/archive-$(date +\%s).tar.gz -C /logs app.log && 
              echo "Cleaning up original log" && 
              > /logs/app.log
            volumeMounts:
              - name: logs
                mountPath: /logs
          restartPolicy: OnFailure
          volumes:
            - name: logs
              persistentVolumeClaim:
                claimName: logs-pvc