apiVersion: v1
kind: Pod
metadata:
  name: list-pod
  namespace: default
spec:
  serviceAccountName: monitoring-sa
  containers:
  - name: kubectl-container
    image: bitnami/kubectl:1.32.2
    command: ["sh", "-c", "sleep 3600"]
