apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kube-critical
spec:
  selector:
    matchLabels:
      app: hello-kube-critical
  template:
    metadata:
      labels:
        app: hello-kube-critical
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                  - key: gpu
                    operator: NotIn
                    values:
                      - "true"
      containers:
        - name: web
          image: aaghamohammadi/hello_kube:1.0.0
