apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sarah-common-developer-binding
  namespace: customer
subjects:
  - kind: User
    name: sarah
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: common-developer
  apiGroup: rbac.authorization.k8s.io
